server.port=8081
spring.application.name=notevault-streams
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
notevault.streams.enabled=${NOTEVAULT_STREAMS_ENABLED:false}
spring.kafka.streams.application-id=notevault-event-counter
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
